run:
  timeout: 5m

linters-settings:
  gosec:
    excludes:
      - G114  # Игнорируем предупреждение о HTTP без TLS (если нужно)
    # Или включить только конкретные проверки:
    # includes:
    #   - G101  # Проверка на hardcoded credentials
    #   - G102  # Проверка на bind to all interfaces

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - gosec

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0