run:
  timeout: 5m

linters-settings:
  gosec:
    # Глобально отключаем определенные проверки Gosec
    excludes:
      - G114  # HTTP без TLS (если вы уверены, что за HTTPS отвечает прокси)

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - gosec

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0