run:
  timeout: 5m

linters-settings:
  gosec:
    # Глобально отключаем определенные проверки Gosec
    excludes:
      - G114  # HTTP без TLS (если вы уверены, что за HTTPS отвечает прокси)
      - G402  # TLS InsecureSkipVerify (или другая проверка, связанная с http3)
      - G403  # TLS MinVersion слишком низкая
      - G404  # Использование слабых шифров
      - G408  # Использование http3.ConfigureTLSConfig
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - gosec

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: "pkg/httpserver/main\\.go"
      linters:
        - gosec
      text: "http3"