services:
  pantan:
    container_name: pantan
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    environment:
      PT_PORT: ${PT_PORT} # порт сервиса
      PT_ENV: ${PT_ENV}
      PT_LOG_LEVEL: ${PT_LOG_LEVEL:-1}
      PT_LOG_FORMAT: ${PT_LOG_FORMAT:-json}
      PT_LOG_TARGET: ${PT_LOG_TARGET:-local}
    ports:
      - "${PT_PORT}:${PT_PORT}"
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./Docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./Docker/prometheus/web.yml:/etc/prometheus/web.yml:ro   # Монтируем файл с паролем
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'   # Активируем аутентификацию
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.listen-address=0.0.0.0:9090'

  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana-data:/var/lib/grafana
      - ./Docker/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-password}
      #- GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - TZ=Europe/Moscow
    restart: unless-stopped

  loki:
    container_name: loki
    image: grafana/loki:latest
    volumes:
      - ./Docker/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"
    command: --config.file=/etc/loki/loki-config.yml
    environment:
      TZ: "Europe/Moscow"
    restart: unless-stopped

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./Docker/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      # Монтируем логи сайта
      - /var/www/www-root/data/www/brend-logo.ru:/logs/brend-logo:ro
    command: --config.file=/etc/promtail/promtail-config.yml
    environment:
      TZ: "Europe/Moscow"
    restart: unless-stopped
volumes:
  grafana-data:
  prometheus-data:
  loki-data: