services:
  pantan:
    container_name: pantan
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PT_PORT: ${PT_PORT} # порт сервиса
      PT_ENV: ${PT_ENV}
      PT_LOG_LEVEL: ${PT_LOG_LEVEL:-1}
      PT_LOG_FORMAT: ${PT_LOG_FORMAT:-json}
      PT_LOG_TARGET: ${PT_LOG_TARGET:-local}
    ports:
      - "${PT_PORT}:${PT_PORT}"
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./Docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana-data:/var/lib/grafana
      - ./Docker/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - TZ=Europe/Moscow
    restart: unless-stopped

  loki:
    container_name: loki
    image: grafana/loki:latest
    volumes:
      - ./Docker/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"
    command: --config.file=/etc/loki/loki-config.yml
    environment:
      TZ: "Europe/Moscow"
    restart: unless-stopped

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./Docker/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      # Монтируем логи хоста
      - /home/vv68/www/brend-logo-droplet/brend-logo2.ru:/logs/brend-logo:ro
    command: --config.file=/etc/promtail/promtail-config.yml
    environment:
      TZ: "Europe/Moscow"
    restart: unless-stopped

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    #network_mode: host
    #pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(proc|sys|dev|run|boot|host|etc)($$|/)'
      - '--collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|tmpfs)$$'
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

volumes:
  grafana-data:
  prometheus-data:
  loki-data: