global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: pantan
    static_configs:
      - targets: ["pantan:8033"]
    metrics_path: /metrics
    scrape_interval: 5s

  #- job_name: 'prometheus'
  #  static_configs:
  #    - targets: ['localhost:9090']

  - job_name: 'brend-logo'
    scrape_interval: 60s
    scrape_timeout: 15s
    scheme: https                                    # ИСПОЛЬЗОВАТЬ HTTPS
    tls_config:
      insecure_skip_verify: true                     # Пропускать проверку сертификата
    static_configs:
      - targets: ['brend-logo.ru:443']
    metrics_path: /metrics
    params:
      format: [prometheus]

  # Мониторинг системных метрик хоста
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
        labels:
          instance: 'brend-logo-server'